apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first
  labels:
    app: first
spec:
  # modifica las réplicas según tu caso de uso
  replicas: 3
  selector:
    matchLabels:
      app: first-pod
  template:
    metadata:
      labels:
        app: first-pod 
    spec:
      containers:
        - name: cont1
          image: python:3.7-alpine
          command: ['sh','-c','echo cont1 > index.html && python -m http.server 8082']
        - name: cont2
          image: python:3.7-alpine
          command: ['sh','-c','echo cont2 > index.html && python -m http.server 8083']