apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  #Solo puede ser coupado por un pod a la vez
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/test"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume2
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  #Solo puede ser coupado por un NODO a la vez
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql"
---
#Una vez ligado a un pv, ya no se puede desligar mas que eliminandolo
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  #Si no se encuentran los selectors, tomara el pv que cumpla el storage y el storageClassName
  selector:
    matchLabels:
      mysql: ready

      

