apiVersion: v1
kind: Secret
metadata:
  name: secret1
stringData:
  username: admon
  password: "1234567"
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: test
          mountPath: /opt
          readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: test
      secret:
        secretName: secret1
        items:
          - key: username
            path: username.txt
            # Solo se montan los items que se especifican en el manifiesto, en este caso no aparece password
