apiVersion: v1
kind: Secret
metadata:
  name: secret1
stringData:
  pass: "1234567"
  user: admon
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: test-container
      image: nginx
      #Enviroment variables
      env:
      - name: PASS
        valueFrom:
          secretKeyRef:
            name: secret1
            key: pass
      - name: USER
        valueFrom:
          secretKeyRef:
            name: secret1
            key: user
      #Volumes
      volumeMounts:
        # name must match the volume name below
        - name: test
          mountPath: /opt
          readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: test
      secret:
        secretName: secret1
        items:
          - key: user
            path: username.txt
            # Solo se montan los items que se especifican en el manifiesto, en este caso no aparece password
